vpc_cidr      = "10.0.0.0/16"
ami_id        = "ami-0f58b397bc5c1f2e8"
instance_type = "t2.micro"
bucket_name = "karthi-dev-terraform-bucket-2026"
subnet_name = "my-subnet"
aws-vpc-name      = "my-vpc"
instance_name = "my-terraform-ec2"
